クリップボードの内容を読み込む-cオプションを実装
fnobi/mdwc pull request #8
Opened 2020-02-04 13:49 UTC by TakamiChie

クリップボードにコピーしているテキストを読み込み、ファイルの代わりに文字数カウントを行う-cオプションを追加しました。
他のMarkdownエディタ環境のテキスト文字数をチェックする時などに利用します。
特に特別な処理は行っていないものの、-lオプションと共存可能です。

2020-02-05 01:17 UTC, fnobi requested changes
いつもありがとうございます！確認しました！

2020-02-05 01:17 UTC, fnobi commented on lib/cli.js
> +        if (argv.h || argv._.length == 0) {
`argv.h` の場合の分岐は、この `argv.c` のif文より先にあった方がよいとおもいます。（-cと-h両方つけた場合にヘルプが表示されない）
`optimist.showHelp()` を２回書くことになっちゃうと思うのですが、まあそれぞれちょっと意味合いが違うのでよいのではないかと。
（というか `argv._.length == 0` の場合は、ヘルプをだすというよりエラーで終了の方が適切かもしれないですね）

2020-02-07 00:18 UTC, TakamiChie commented
修正してみました

2020-02-07 14:30 UTC, fnobi requested changes
細かいところで恐縮ですが、２個ほどコメント付けました！

2020-02-07 14:30 UTC, fnobi commented on lib/cli.js
> +	}else if (argv.c) {
この行がインデントずれているようなので、他の節と揃えたいです！

2020-02-07 14:30 UTC, fnobi commented on lib/cli.js
> +    }else if (argv.v) {
`argv.v` のケースにおいては、当てはまる場合はreturnしているので、後ろの節をelse ifで繋がなくても、独立したifで置いてしまってもよいかもしれません。

2020-02-09 13:27 UTC, TakamiChie commented
一つ目の指摘に対応しました。
二つ目ですが、notepadで確認しても特に不審な点が見つからなかったため、巻き添えで治ったものと思われます。

2020-02-10 04:21 UTC, nobii approved these changes
いいと思います！レビューにもお付き合い頂きありがとうございます。

2020-02-10 04:21 UTC, merged